/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodbankapp.presentation;

import foodbankapp.EncryptionMgr;
import foodbankapp.ResourceMgr;
import foodbankapp.domain.*;
import javax.swing.JOptionPane;
import foodbankapp.service.AccountSvcCacheImpl;
import java.util.Arrays;
import java.util.logging.Logger;


/**
 *
 * @author Brian
 */
public class CreateAccountUI extends javax.swing.JFrame {

    /**
     * Creates new form createAccount
     */
    public CreateAccountUI() {
        mgr = ResourceMgr.instance();
        initComponents();
    }
    
    private static final Logger LOGGER = 
            Logger.getLogger(CreateAccountUI.class.getName());
    
    private ResourceMgr mgr;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        fullNameFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emailFld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        usernameFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create a New User");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        confirmBtn.setBackground(new java.awt.Color(204, 204, 204));
        confirmBtn.setText(mgr.string("confirm"));
        confirmBtn.setToolTipText(mgr.string("confirmHint")
        );
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(204, 204, 204));
        cancelBtn.setText(mgr.string("cancel"));
        cancelBtn.setToolTipText(mgr.string("cancelHint")
        );
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        fullNameFld.setToolTipText(mgr.string("nameHint"));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setLabelFor(fullNameFld);
        jLabel1.setText(mgr.string("name"));

        emailFld.setToolTipText(mgr.string("emailHint"));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setLabelFor(emailFld);
        jLabel2.setText(mgr.string("email"));

        usernameFld.setToolTipText(mgr.string("usernameHint"));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(mgr.string("username"));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setLabelFor(jPasswordField1);
        jLabel4.setText(mgr.string("password"));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText(mgr.string("createNewUser"));
        jLabel5.setToolTipText(mgr.string("createNewUserHint"));

        jPasswordField1.setToolTipText(mgr.string("passwordHint")
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameFld)
                            .addComponent(emailFld, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(fullNameFld)
                            .addComponent(jPasswordField1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(confirmBtn)
                        .addGap(28, 28, 28)
                        .addComponent(cancelBtn)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        confirmBtn.getAccessibleContext().setAccessibleDescription(null);
        cancelBtn.getAccessibleContext().setAccessibleDescription("mgr.string(\"cancelHint\")");
        fullNameFld.getAccessibleContext().setAccessibleName(mgr.string("name")
        );
        fullNameFld.getAccessibleContext().setAccessibleDescription(mgr.string("nameHint"));
        emailFld.getAccessibleContext().setAccessibleName(mgr.string("email")
        );
        emailFld.getAccessibleContext().setAccessibleDescription(mgr.string("emailHint"));
        usernameFld.getAccessibleContext().setAccessibleName(mgr.string("username")
        );
        usernameFld.getAccessibleContext().setAccessibleDescription(mgr.string("usernameHint")
        );
        jLabel4.getAccessibleContext().setAccessibleName(null);
        jLabel4.getAccessibleContext().setAccessibleDescription(null);
        jPasswordField1.getAccessibleContext().setAccessibleName(mgr.string("password")
        );
        jPasswordField1.getAccessibleContext().setAccessibleDescription(mgr.string("passwordHint"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        
        final String iv = "2163243567289329"; // This has to be 16 characters
        final String secretKey = "foodBankApp.secret";
        EncryptionMgr mgrEncrypt = new EncryptionMgr();
        final String clearPassword = Arrays.toString(jPasswordField1.getPassword());
        final String encryptedPassword = mgrEncrypt.encrypt(clearPassword,iv,secretKey);
        
        Login login = new Login();
        login.setUsername(usernameFld.getText());
        login.setPassword(encryptedPassword);
        if (!login.validate()){
            JOptionPane.showMessageDialog(this, 
                    mgr.string("loginError1"), mgr.string("error"), 
                    JOptionPane.ERROR_MESSAGE);
            return;
          
        }
        
        Account account = new Account();
        account.setName(fullNameFld.getText());
        account.setEmail(emailFld.getText());
        account.setLogin(login);
        //I had intended on implementing some security using this variable, 
        //however, not going to use it right now. by end of project will add
        //or will remove from Account object and any related logic
        account.setSecurityLevel("user");
        boolean isValid = account.validate();
        if (!isValid){
            JOptionPane.showMessageDialog(this, 
                    mgr.string("createAcctError"), mgr.string("error"), 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            AccountSvcCacheImpl impl = AccountSvcCacheImpl.getInstance();
            account = impl.create(account);
            JOptionPane.showMessageDialog(this, 
                    mgr.string("createAcctMsg"),
                    mgr.string("createAcctMsgTitle"), JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            LoginUI loginUI = new LoginUI();
            loginUI.setVisible(true);
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
              
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField emailFld;
    private javax.swing.JTextField fullNameFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField usernameFld;
    // End of variables declaration//GEN-END:variables
}
