/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodbankapp.presentation;

import foodbankapp.ResourceMgr;
import foodbankapp.domain.*;
import java.util.*;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class DispenseUI extends javax.swing.JFrame {

    private Account account = null;
    private int itemID = 0;
    private List<Inventory> inventory;
    private static final Logger LOGGER = 
            Logger.getLogger(CreateAccountUI.class.getName());
    
    private ResourceMgr mgr;
    
    public void setAccount(Account account){
        this.account = account;
    }
    
    public void setItem(int item){
        this.itemID = item;
    }    
    
    public DispenseUI(){
        mgr = ResourceMgr.instance();
        initComponents();
    }
    
    public DispenseUI(Account account, int itemID) {
        mgr = ResourceMgr.instance();
        initComponents();
        this.account = account;
        this.itemID = itemID;
        inventory = account.getInventory();
        Inventory item = inventory.get(itemID);
        itemNameFld.setText(item.getName());
        itemAmountFld.setText(String.valueOf(item.getAmount()));
        itemUnitLbl.setText(item.getUnit());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dispenseFld = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        itemAmountFld = new javax.swing.JTextField();
        itemUnitLbl = new javax.swing.JLabel();
        itemNameFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Amount");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(mgr.string("amountFldLbl"));

        dispenseFld.setToolTipText(mgr.string("amountFldHint"));

        confirmButton.setBackground(new java.awt.Color(255, 255, 255));
        confirmButton.setText(mgr.string("confirm")
        );
        confirmButton.setToolTipText(mgr.string("confirmHint")
        );
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText(mgr.string("cancel"));
        cancelBtn.setToolTipText(mgr.string("cancelHint")
        );
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        itemAmountFld.setToolTipText(mgr.string("amountDisp"));

        itemNameFld.setToolTipText(mgr.string("itemDisp"));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(mgr.string("itemName"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dispenseFld)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(itemUnitLbl))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemAmountFld, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(itemUnitLbl)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(itemAmountFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dispenseFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelBtn))
                .addGap(47, 47, 47))
        );

        jLabel1.getAccessibleContext().setAccessibleName(mgr.string("amountFldLbl"));
        jLabel1.getAccessibleContext().setAccessibleDescription(mgr.string("amountFldHint"));
        dispenseFld.getAccessibleContext().setAccessibleName(mgr.string("amount"));
        dispenseFld.getAccessibleContext().setAccessibleDescription(mgr.string("amountFldHint"));
        confirmButton.getAccessibleContext().setAccessibleName(mgr.string("confirm"));
        confirmButton.getAccessibleContext().setAccessibleDescription(mgr.string("confirmHint")
        );
        cancelBtn.getAccessibleContext().setAccessibleName(mgr.string("cancel"));
        cancelBtn.getAccessibleContext().setAccessibleDescription(mgr.string("cancelHint"));
        itemAmountFld.getAccessibleContext().setAccessibleName(mgr.string("amount")
        );
        itemAmountFld.getAccessibleContext().setAccessibleDescription(mgr.string("amountDisp")
        );
        itemNameFld.getAccessibleContext().setAccessibleName(mgr.string("itemName"));
        itemNameFld.getAccessibleContext().setAccessibleDescription(mgr.string("itemDisp")
        );
        jLabel3.getAccessibleContext().setAccessibleName(mgr.string("itemName"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        int editAmount = Integer.parseInt(dispenseFld.getText());
        if (editAmount >= 0){
        Inventory item = inventory.get(itemID);
        item.setAmount(item.getAmount()-editAmount);
        JOptionPane.showMessageDialog(this, mgr.string("dispensedMsg") 
                + " " + editAmount + " " + item.getUnit()  +
                " of " + item.getName(), mgr.string("itemUpdatedMsg"), 
                JOptionPane.INFORMATION_MESSAGE);
        this.account.setInventory(inventory);
        Date date = new Date();
        Transaction transaction = 
                new Transaction(item.getName(), date, editAmount, item.getLocation());
        this.account.add(transaction);
        System.out.println(account.getTransactions().toString());
        this.setVisible(false);
        MainUI mainUI = new MainUI();
        mainUI.setAccount(account);
        mainUI.setVisible(true);
        }else{
           JOptionPane.showMessageDialog(this, 
                     mgr.string("negativeNumError"), mgr.string("error"),
                     JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);
        MainUI mainUI = new MainUI();
        mainUI.setAccount(account);
        mainUI.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DispenseUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField dispenseFld;
    private javax.swing.JTextField itemAmountFld;
    private javax.swing.JTextField itemNameFld;
    private javax.swing.JLabel itemUnitLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
