/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodbankapp.presentation;

import foodbankapp.ResourceMgr;
import foodbankapp.domain.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class GetTrendDataUI extends javax.swing.JFrame {

    private Account account = null;
    private List<Transaction> transactions = new LinkedList<Transaction>();
    private LocationComboBoxModel combo = new LocationComboBoxModel();
    private TransactionTableModel model = new TransactionTableModel();
    private static final Logger LOGGER = 
            Logger.getLogger(CreateAccountUI.class.getName());
    
    private ResourceMgr mgr;
    private int selectedRow = -1;
    
    public void setAccount(Account account){
        this.account = account;
        model.setTransactions(account.getTransactions());
        combo.setLocations(account.getLocations());
    }
    public GetTrendDataUI() {
        mgr = ResourceMgr.instance();
        String[] names = {
            mgr.string("itemName"),
            mgr.string("amount"),
            mgr.string("date")
        };
        model.setColumnNames(names);
        initComponents();
        transactionTable.setModel(model);
        
    }
    public GetTrendDataUI(Account account) {
        mgr = ResourceMgr.instance();
        initComponents();
        this.account = account;
        transactions = account.getTransactions();
        model.setTransactions(transactions);
        transactionTable.setModel(model);
        combo.setLocations(account.getLocations());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startDateFld = new javax.swing.JFormattedTextField();
        endDateFld = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LocationComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        startDateFld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        startDateFld.setText("xx/xx/xx");
        startDateFld.setToolTipText(mgr.string("startDateHint")
        );

        endDateFld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        endDateFld.setText("xx/xx/xx");
        endDateFld.setToolTipText(mgr.string("endDateHint")
        );

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setLabelFor(startDateFld);
        jLabel1.setText(mgr.string("startDate"));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setLabelFor(endDateFld);
        jLabel2.setText(mgr.string("endDate")
        );

        transactionTable.setBackground(new java.awt.Color(255, 255, 255));
        transactionTable.setModel(model);
        jScrollPane1.setViewportView(transactionTable);
        transactionTable.getAccessibleContext().setAccessibleName("mgr.string(\"transactionTbl\")");
        transactionTable.getAccessibleContext().setAccessibleDescription("mgr.string(\"transactionTblHint\")");

        updateBtn.setBackground(new java.awt.Color(204, 204, 204));
        updateBtn.setText(mgr.string("update")
        );
        updateBtn.setToolTipText(mgr.string("transactionUpdateHint")
        );
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setText(mgr.string("back")
        );
        backBtn.setToolTipText(mgr.string("backHint")
        );
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(mgr.string("trend")
        );

        LocationComboBox.setModel(combo);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText(mgr.string("location")
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(updateBtn)
                        .addGap(110, 110, 110)
                        .addComponent(backBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(backBtn))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        startDateFld.getAccessibleContext().setAccessibleDescription(mgr.string("startDateHint")
        );
        endDateFld.getAccessibleContext().setAccessibleName(mgr.string("endDate")
        );
        endDateFld.getAccessibleContext().setAccessibleDescription(mgr.string("endDateHint")
        );
        jLabel1.getAccessibleContext().setAccessibleName(mgr.string("startDate")
        );
        jLabel2.getAccessibleContext().setAccessibleName(mgr.string("endDate")
        );
        updateBtn.getAccessibleContext().setAccessibleName(mgr.string("update")
        );
        updateBtn.getAccessibleContext().setAccessibleDescription(mgr.string("transactionUpdateHint")
        );
        backBtn.getAccessibleContext().setAccessibleName(mgr.string("back")
        );
        backBtn.getAccessibleContext().setAccessibleDescription(mgr.string("backHint")
        );
        jLabel3.getAccessibleContext().setAccessibleName(mgr.string("trend")
        );
        jLabel3.getAccessibleContext().setAccessibleDescription(mgr.string("trendHint")
        );
        LocationComboBox.getAccessibleContext().setAccessibleName(mgr.string("location")
        );
        LocationComboBox.getAccessibleContext().setAccessibleDescription(mgr.string("locationListHint")
        );
        jLabel4.getAccessibleContext().setAccessibleName(mgr.string("location")
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            Date begin =
                    new SimpleDateFormat("dd/MM/yy").parse(startDateFld.getText());
            Date end =
                    new SimpleDateFormat("dd/MM/yy").parse(endDateFld.getText());
            transactions = account.getTransactions();
            ListIterator<Transaction> iter = transactions.listIterator();
            while (iter.hasNext()){
                Transaction trans = iter.next();
                if ((trans.getDate().before(begin)) || trans.getDate().after(end)){
                    transactions.remove(trans);
                }
                if (!(trans.getLocation().getName().equals(LocationComboBox.getSelectedIndex()))){
                    transactions.remove(trans);
                }
            }
            if (transactions.size() > 0){
                model.setTransactions(transactions);
                model.fireTableDataChanged();
            }else{
                JOptionPane.showMessageDialog(this, 
                     mgr.string("noEntryError"), mgr.string("error"),
                     JOptionPane.ERROR_MESSAGE);
                transactions = account.getTransactions();
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, 
                     mgr.string("dateError"), mgr.string("error"),
                     JOptionPane.ERROR_MESSAGE);
        }
             
    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        MainUI mainUI = new MainUI();
        mainUI.setAccount(account);
        mainUI.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetTrendDataUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LocationComboBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JFormattedTextField endDateFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField startDateFld;
    private javax.swing.JTable transactionTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
